services:
  app:
    container_name: app
    build:
      context: ../todo
      dockerfile: ../infra/Dockerfile
    volumes:
      - ../todo:/todo
      - node_modules_volume:/todo/node_modules
    ports:
      - 4002:3000
    command: sh -c "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume:

